# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assg_2_gui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(808, 649)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chooseimage = QtGui.QPushButton(self.centralwidget)
        self.chooseimage.setObjectName(_fromUtf8("chooseimage"))
        self.verticalLayout.addWidget(self.chooseimage)
        self.save = QtGui.QPushButton(self.centralwidget)
        self.save.setObjectName(_fromUtf8("save"))
        self.verticalLayout.addWidget(self.save)
        self.undoall = QtGui.QPushButton(self.centralwidget)
        self.undoall.setObjectName(_fromUtf8("undoall"))
        self.verticalLayout.addWidget(self.undoall)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.psnr = QtGui.QPushButton(self.centralwidget)
        self.psnr.setObjectName(_fromUtf8("psnr"))
        self.horizontalLayout_7.addWidget(self.psnr)
        self.psnrdisp = QtGui.QLabel(self.centralwidget)
        self.psnrdisp.setObjectName(_fromUtf8("psnrdisp"))
        self.horizontalLayout_7.addWidget(self.psnrdisp)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ssim = QtGui.QPushButton(self.centralwidget)
        self.ssim.setObjectName(_fromUtf8("ssim"))
        self.horizontalLayout_8.addWidget(self.ssim)
        self.ssimdisp = QtGui.QLabel(self.centralwidget)
        self.ssimdisp.setObjectName(_fromUtf8("ssimdisp"))
        self.horizontalLayout_8.addWidget(self.ssimdisp)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.blurkernel = QtGui.QGroupBox(self.centralwidget)
        self.blurkernel.setObjectName(_fromUtf8("blurkernel"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.blurkernel)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.kernel1 = QtGui.QRadioButton(self.blurkernel)
        self.kernel1.setObjectName(_fromUtf8("kernel1"))
        self.verticalLayout_7.addWidget(self.kernel1)
        self.kernel2 = QtGui.QRadioButton(self.blurkernel)
        self.kernel2.setObjectName(_fromUtf8("kernel2"))
        self.verticalLayout_7.addWidget(self.kernel2)
        self.kernel3 = QtGui.QRadioButton(self.blurkernel)
        self.kernel3.setObjectName(_fromUtf8("kernel3"))
        self.verticalLayout_7.addWidget(self.kernel3)
        self.kernel4 = QtGui.QRadioButton(self.blurkernel)
        self.kernel4.setObjectName(_fromUtf8("kernel4"))
        self.verticalLayout_7.addWidget(self.kernel4)
        self.unknownkernel = QtGui.QRadioButton(self.blurkernel)
        self.unknownkernel.setObjectName(_fromUtf8("unknownkernel"))
        self.verticalLayout_7.addWidget(self.unknownkernel)
        self.verticalLayout_6.addWidget(self.blurkernel)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.fullinverse = QtGui.QPushButton(self.centralwidget)
        self.fullinverse.setObjectName(_fromUtf8("fullinverse"))
        self.verticalLayout.addWidget(self.fullinverse)
        self.truncinv = QtGui.QPushButton(self.centralwidget)
        self.truncinv.setObjectName(_fromUtf8("truncinv"))
        self.verticalLayout.addWidget(self.truncinv)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radius = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radius.sizePolicy().hasHeightForWidth())
        self.radius.setSizePolicy(sizePolicy)
        self.radius.setObjectName(_fromUtf8("radius"))
        self.horizontalLayout_4.addWidget(self.radius)
        self.radiusval = QtGui.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusval.sizePolicy().hasHeightForWidth())
        self.radiusval.setSizePolicy(sizePolicy)
        self.radiusval.setObjectName(_fromUtf8("radiusval"))
        self.horizontalLayout_4.addWidget(self.radiusval)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.weiner = QtGui.QPushButton(self.centralwidget)
        self.weiner.setObjectName(_fromUtf8("weiner"))
        self.verticalLayout.addWidget(self.weiner)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.k = QtGui.QLabel(self.centralwidget)
        self.k.setObjectName(_fromUtf8("k"))
        self.horizontalLayout_5.addWidget(self.k)
        self.kval = QtGui.QDoubleSpinBox(self.centralwidget)
        self.kval.setObjectName(_fromUtf8("kval"))
        self.horizontalLayout_5.addWidget(self.kval)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.constls = QtGui.QPushButton(self.centralwidget)
        self.constls.setObjectName(_fromUtf8("constls"))
        self.verticalLayout.addWidget(self.constls)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.y = QtGui.QLabel(self.centralwidget)
        self.y.setObjectName(_fromUtf8("y"))
        self.horizontalLayout_6.addWidget(self.y)
        self.yval = QtGui.QDoubleSpinBox(self.centralwidget)
        self.yval.setObjectName(_fromUtf8("yval"))
        self.horizontalLayout_6.addWidget(self.yval)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.blurredview = QtGui.QGraphicsView(self.centralwidget)
        self.blurredview.setObjectName(_fromUtf8("blurredview"))
        self.verticalLayout_4.addWidget(self.blurredview)
        self.blurred = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blurred.sizePolicy().hasHeightForWidth())
        self.blurred.setSizePolicy(sizePolicy)
        self.blurred.setObjectName(_fromUtf8("blurred"))
        self.verticalLayout_4.addWidget(self.blurred)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.deblurredview = QtGui.QGraphicsView(self.centralwidget)
        self.deblurredview.setObjectName(_fromUtf8("deblurredview"))
        self.verticalLayout_5.addWidget(self.deblurredview)
        self.deblurred = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deblurred.sizePolicy().hasHeightForWidth())
        self.deblurred.setSizePolicy(sizePolicy)
        self.deblurred.setObjectName(_fromUtf8("deblurred"))
        self.verticalLayout_5.addWidget(self.deblurred)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.chooseimage.setText(_translate("MainWindow", "Choose image", None))
        self.save.setText(_translate("MainWindow", "Save", None))
        self.undoall.setText(_translate("MainWindow", "Undo All", None))
        self.psnr.setText(_translate("MainWindow", "PSNR", None))
        self.psnrdisp.setText(_translate("MainWindow", "TextLabel", None))
        self.ssim.setText(_translate("MainWindow", "SSIM", None))
        self.ssimdisp.setText(_translate("MainWindow", "TextLabel", None))
        self.blurkernel.setTitle(_translate("MainWindow", "Blur Kernel", None))
        self.kernel1.setText(_translate("MainWindow", "Kernel 1", None))
        self.kernel2.setText(_translate("MainWindow", "Kernel 2", None))
        self.kernel3.setText(_translate("MainWindow", "Kernel 3", None))
        self.kernel4.setText(_translate("MainWindow", "Kernel 4", None))
        self.unknownkernel.setText(_translate("MainWindow", "Unknown kernel", None))
        self.fullinverse.setText(_translate("MainWindow", "Full inverse filter", None))
        self.truncinv.setText(_translate("MainWindow", "Truncated inverse filter", None))
        self.radius.setText(_translate("MainWindow", "Radius", None))
        self.weiner.setText(_translate("MainWindow", "Weiner filter", None))
        self.k.setText(_translate("MainWindow", "K", None))
        self.constls.setText(_translate("MainWindow", "Constrained least square filter", None))
        self.y.setText(_translate("MainWindow", "Y", None))
        self.blurred.setText(_translate("MainWindow", "Blurred image", None))
        self.deblurred.setText(_translate("MainWindow", "Deblurred image", None))

